### ISSUE TITLE
Missing data files.

### ISSUE THREAD

**Issue by mrbeann** [collwe/JEDI-Crowd-Teaching#5]
Very interesting paper:+1:, and I have tried to run this myself, But it seems the code can't run, missing lot's of files

E.g.
../Datasets/nhm-butterfly/class_names.npy'
DATASET['Horse'] = sio.loadmat('/home/stethox/JEDI_KDD18/data/data_horse_JEDI_full_forArun.mat')

Can you check this?

Thanks!

**Comment by collwe** [comment]
For MATLAB code, simply set the value of the variable 'loadData=false' (in the file of demo_learners.m) will do the work. You can run the main function with this change.
